export const CONTACT_SUBMIT_SUCCESS = 'CONTACT_SUBMIT_SUCCESS';
export const CONTACT_SUBMIT_FAILURE = 'CONTACT_SUBMIT_FAILURE';
export const CONTACTS_RETURN_SUCCESS = 'CONTACTS_RETURN_SUCCESS';
export const CONTACTS_RETURN_FAILURE = 'CONTACTS_RETURN_FAILURE';
export const BEGIN_FETCH = 'BEGIN_FETCH';
export const FETCH_FAIL = 'FETCH_FAIL';